# Generated by Django 5.2 on 2025-04-14 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last name')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid number!', regex='^01[0-2,5]{1}[0-9]{8}$')])),
                ('preferred_time_start', models.TimeField()),
                ('preferred_time_end', models.TimeField()),
                ('linkedIn', models.URLField()),
                ('github', models.URLField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
