# Generated by Django 5.2 on 2025-04-15 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='github',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='Enter a valid github url!', regex='^https://github.com/')]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedIn',
            field=models.URLField(validators=[django.core.validators.RegexValidator(message='Enter a valid linkedIn url!', regex='^https://linkedin.com/')]),
        ),
    ]
